var emotions = [
"钦佩(admirtation)",
"爱慕(adoration)",
"欣赏(aesthetic)",
"感谢(appreciation)",
"玩笑(amusement)",
"愤怒(anger)",
"焦虑(anxiety)",
"敬畏(awe)",
"尴尬(awkwardness)",
"厌倦(boredom)",
"平静(calmness)",
"困惑(confusion)",
"渴望(carving)",
"厌恶(disgust)",
"同情(empathic pain)",
"走神(entrancement)",
"激动(excitement)",
"害怕(fear)",
"恐惧(horror)",
"好奇(interest)",
"欢乐(joy)",
"怀旧(nostalgia)",
"释然(relief)",
"悲伤(sadness)",
"满足(satisfaction)",
"饥渴(sexual desire)",
"吃惊(surprise)"
];