var occupations = [
"acountant<br/>会计",
"actor<br/>男演员",
"actress<br/>女演员",
"airline representative<br/>地勤人员",
"anchor<br/>新闻主播",
"announcer<br/>广播员",
"archaeologist<br/>考古学家",
"architect<br/>建筑师",
"artist<br/>艺术家",
"astronaut<br/>宇航员",
"astropologist<br/>人类学家",
"attendant<br/>服务员",
"auditor<br/>审计员",
"auto mechanic<br/>汽车技工",
"baker<br/>面包师",
"ballerina<br/>芭蕾舞星",
"barber<br/>理发师",
"baseball player<br/>棒球选手",
"beautician<br/>美容师",
"bell boy<br/>门童",
"bellhop<br/>旅馆的行李员",
"binman<br/>清洁工,垃圾工",
"biologist<br/>生物学家",
"blacksmith<br/>铁匠",
"bootblack<br/>擦鞋童",
"botanist<br/>植物学家",
"boxer<br/>拳击手",
"broker (agent)<br/>经纪人",
"budgeteer<br/>预算编制者",
"bus driver<br/>公车(巴士)司机",
"businessman<br/>实业家,商人",
"butcher<br/>肉贩",
"captain<br/>船长,机长",
"car mechanic<br/>汽车修理师",
"carpenter<br/>木匠",
"cartoonist<br/>漫画家",
"cashier<br/>出纳员",
"chef<br/>厨师长",
"chemist<br/>化学家",
"clerk<br/>店员",
"clown<br/>小丑",
"composer<br/>作曲家",
"computer programmer<br/>程序员",
"conductor<br/>车长",
"construction worker<br/>建筑工人",
"cook<br/>厨师",
"copywriter<br/>撰稿人",
"cowboy<br/>牛仔",
"customs officer<br/>海关官员",
"cutter<br/>裁剪师",
"dancer<br/>舞者",
"delivery boy<br/>送报员",
"dentist<br/>牙科医生",
"designer<br/>设计师",
"desk clerk<br/>接待员",
"detective<br/>刑警",
"director<br/>导演",
"doctor<br/>医生",
"door-to-door salesman<br/>推销员",
"driver<br/>司机",
"driver<br/>驾驶员",
"dustman<br/>清洁工",
"economist<br/>经济学家",
"editor<br/>编辑",
"electrician<br/>电工",
"engineer<br/>工程师",
"expert on folklore<br/>民俗学家",
"farmer<br/>农夫",
"fashion designer<br/>时装设计师",
"firefighter<br/>消防员",
"fisherman<br/>渔夫",
"fish-monger<br/>鱼贩",
"florist<br/>卖花人",
"florist<br/>花商",
"Foreign minister<br/>外交部长",
"forman<br/>工头",
"futurologist<br/>未来学家",
"gardener<br/>园丁",
"geologist<br/>地质学家",
"graphic designer<br/>美术设计员",
"greengrocer<br/>菜贩",
"guard<br/>警卫",
"guide<br/>导游",
"headmaster<br/>中小学的男校长",
"headmistress<br/>中小学的女校长",
"housekeeper<br/>管家",
"housewife<br/>家庭主妇",
"illustrator<br/>汇稿员",
"janitor<br/>清洁工",
"journalist<br/>记者",
"judge<br/>法官",
"key puncher<br/>电脑操作员",
"lawyer<br/>律师",
"lecturer<br/>讲师",
"linguist<br/>语言学家",
"mailman<br/>邮差",
"mathematician<br/>数学家",
"merchant<br/>商人",
"meson<br/>石匠",
"milkman<br/>送奶人",
"model<br/>模特",
"monk<br/>和尚,教士",
"movie star<br/>电影明星",
"musician<br/>音乐家",
"national public servant<br/>国家公务员",
"newscaster<br/>新闻评论人",
"newspaper boy<br/>报童",
"novelist<br/>小说家",
"nun<br/>尼姑",
"nurse<br/>护士",
"office staff<br/>上班族",
"oil supplier<br/>加油工",
"operator<br/>接线员",
"painter<br/>画家",
"parachutist<br/>跳伞人",
"pedlar 小贩,商贩<br/>",
"personnel<br/>职员",
"pharmacist<br/>药剂师",
"philosopher<br/>哲学家",
"photographer<br/>摄影师",
"physicist<br/>物理学家",
"physiologist<br/>生理学家",
"pilot<br/>飞行员",
"playwright<br/>剧作家",
"poet<br/>诗人",
"policeman<br/>警察",
"politician<br/>政治学家",
"porter<br/>行李夫",
"postal clerk<br/>邮政人员",
"postman<br/>邮差",
"President<br/>总统",
"priest<br/>牧师",
"probationer<br/>试用人员,练习生",
"processfor<br/>教授",
"producer<br/>制片人",
"programmer<br/>电脑程序员",
"public servants<br/>公务员",
"publisher<br/>出版人员",
"estate agent<br/>房地产经纪人",
"receptionist<br/>接待员",
"repairman<br/>修理工人",
"reporter<br/>记者",
"sailor<br/>船员，水手",
"salesman<br/>售货员",
"saleswoman<br/>女店员",
"scholar<br/>学者",
"scientist<br/>科学家",
"sculptor<br/>雕刻家",
"secretary<br/>秘书",
"sewer<br/>裁缝师",
"singer<br/>歌手",
"soldiery<br/>士兵,军人",
"stewardess<br/>空中小姐",
"tailor<br/>裁缝师",
"talent<br/>星探",
"taxi<br/>driver计程车司机",
"teacher<br/>教师",
"technician<br/>技术人员",
"telephone operator<br/>电话接线员",
"tour guide<br/>导游",
"tracer<br/>绘图员",
"tradesman<br/>零售商人,小商人",
"translator<br/>翻译家",
"typist<br/>打字员",
"zoologist<br/>动物学家",
];