var occupations = [
"acountant 会计",
"actor 男演员",
"actress 女演员",
"airline representative 地勤人员",
"anchor 新闻主播",
"announcer 广播员",
"archaeologist 考古学家",
"architect 建筑师",
"artist 艺术家",
"astronaut 宇航员",
"astropologist 人类学家",
"attendant 服务员",
"auditor 审计员",
"auto mechanic 汽车技工",
"baker 面包师",
"ballerina 芭蕾舞星",
"barber 理发师",
"baseball player 棒球选手",
"beautician 美容师",
"bell boy 门童",
"bellhop 旅馆的行李员",
"binman 清洁工,垃圾工",
"biologist 生物学家",
"blacksmith 铁匠",
"bootblack 擦鞋童",
"botanist 植物学家",
"boxer 拳击手",
"broker (agent) 经纪人",
"budgeteer 预算编制者",
"bus driver 公车(巴士)司机",
"businessman 实业家,商人",
"butcher 肉贩",
"captain 船长,机长",
"car mechanic 汽车修理师",
"carpenter 木匠",
"cartoonist 漫画家",
"cashier 出纳员",
"chef 厨师长",
"chemist 化学家",
"clerk 店员",
"clown 小丑",
"composer 作曲家",
"computer programmer 程序员",
"conductor 车长",
"construction worker 建筑工人",
"cook 厨师",
"copywriter 撰稿人",
"cowboy 牛仔",
"customs officer 海关官员",
"cutter 裁剪师",
"dancer 舞者",
"delivery boy 送报员",
"dentist 牙科医生",
"designer 设计师",
"desk clerk 接待员",
"detective 刑警",
"director 导演",
"doctor 医生",
"door-to-door salesman 推销员",
"driver 司机",
"driver驾驶员",
"druggist, chemist, pharmacist 药剂师",
"dustman 清洁工",
"economist 经济学家",
"editor 编辑",
"electrician 电工",
"engineer 工程师",
"expert on folklore 民俗学家",
"farmer 农夫",
"fashion designer 时装设计师",
"firefighter 消防员",
"fisherman 渔夫",
"fish-monger 鱼贩",
"florist 卖花人",
"florist 花商 ",
"Foreign minister 外交部长",
"forman 工头",
"futurologist 未来学家",
"gardener 园丁",
"geologist 地质学家",
"graphic designer 美术设计员",
"greengrocer 菜贩",
"guard 警卫",
"guide 导游",
"headmaster 中小学的男校长",
"headmistress 中小学的女校长",
"housekeeper 管家",
"housewife 家庭主妇",
"illustrator 汇稿员",
"janitor 清洁工",
"journalist 记者",
"judge 法官",
"key puncher 电脑操作员",
"lawyer 律师",
"lecturer 讲师",
"linguist 语言学家",
"mailman 邮差",
"mathematician 数学家",
"merchant 商人",
"meson 石匠",
"milkman 送奶人",
"model 模特",
"monk 和尚,教士",
"movie star 电影明星",
"musician 音乐家",
"national public servant 国家公务员",
"newscaster 新闻评论人",
"newspaper boy 报童",
"novelist 小说家",
"nun 尼姑",
"nurse 护士",
"office staff 上班族",
"oil supplier 加油工",
"operator 接线员",
"painter 画家",
"parachutist 跳伞人",
"pedlar 小贩,商贩 ",
"personnel 职员",
"pharmacist 药剂师",
"philosopher 哲学家",
"photographer 摄影师",
"physicist 物理学家",
"physiologist 生理学家",
"pilot 飞行员",
"playwright 剧作家",
"poet 诗人",
"policeman 警察",
"politician 政治学家",
"porter 行李夫",
"postal clerk 邮政人员",
"postman 邮差",
"President 总统",
"priest 牧师",
"probationer 试用人员,练习生",
"processfor 教授",
"producer 制片人",
"programmer 电脑程序员",
"public servants 公务员",
"publisher 出版人员",
"real estate agent 房地产经纪人",
"receptionist 接待员",
"repairman 修理工人",
"reporter 记者",
"sailor 船员，水手",
"salesman 售货员",
"saleswoman 女店员",
"scholar 学者",
"scientist 科学家",
"sculptor 雕刻家",
"secretary 秘书",
"sewer 裁缝师",
"singer 歌手",
"soldiery 士兵,军人",
"stewardess 空中小姐",
"tailor 裁缝师",
"talent 星探",
"taxi driver计程车司机",
"teacher 教师",
"technician 技术人员",
"telephone operator 电话接线员",
"tour guide 导游",
"tracer 绘图员",
"tradesman 零售商人,小商人",
"translator 翻译家",
"typist 打字员",
"zoologist 动物学家",
];